version: '3'

services:
  django_app: #can be any name, this name should match in default conf
    volumes:
      - static_vol:/app/sub_app/static
    #   - media_vol:/app/sub_app/media
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: portfolio_postgres
    env_file:
      - .env
    volumes:
      - sqldb:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    command: -p 5433
  

volumes:
  static_vol:
  sqldb:
#   media_vol:

