version: '3'
services:
  django_app:
    container_name: my-portfolio-app
    volumes:
      - static_vol:/app/sub_app/static
    env_file:
      - .env
    build:
      context: .
    #ports:
    #  - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - sqldb:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  static_vol:
  sqldb:

networks:
  mynetwork:
    external: true
