version: '3'

services:
  django_app: #can be any name, this name should match in default conf
    volumes:
      - static_vol:/app/sub_app/static
    #   - media_vol:/app/sub_app/media
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    volumes:
      - static_vol:/app/sub_app/static
    #   - media_vol:/app/sub_app/media
    ports:
      - "8080:80"
    depends_on:
      - django_app

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - sqldb:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  static_vol:
  sqldb:
#   media_vol:


# @as i am using S3 for media file, so i dont need ngign to server them./