# Generated by Django 4.0.6 on 2022-07-22 10:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCat',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('abstract', ckeditor.fields.RichTextField()),
                ('date', models.DateField()),
                ('publisher', models.CharField(max_length=200)),
                ('paper_url', models.CharField(max_length=100)),
                ('github_url', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_app.category')),
            ],
        ),
    ]
