# Generated by Django 4.0.6 on 2022-07-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0002_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cat',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='slug',
        ),
    ]
