# Generated by Django 4.0.6 on 2022-07-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0002_papercat_papers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='papercat',
            options={'verbose_name_plural': 'PaperCategories'},
        ),
        migrations.AlterModelOptions(
            name='papers',
            options={'verbose_name_plural': 'PapersPublished'},
        ),
    ]
