# Generated by Django 4.0.6 on 2022-07-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0003_rename_url_category_slug_rename_cat_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='summary',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
