# Generated by Django 4.0.6 on 2022-07-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0004_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
