# Generated by Django 4.0.6 on 2022-07-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0005_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='github_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
